# fly.toml app configuration file generated for sofi on 2024-09-02T15:54:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sofi'
primary_region = 'lhr'

[build]
  [build.args]
    GO_VERSION = '1.22.5'

[env]
  SOFI_PORT = '8080'
  SOFI_TEMPLATE_DIR = '/usr/local/bin/templates'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
